version: '3'
services:
  postgres:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: postgres
    volumes:
      - "/data/postgres:/var/lib/postgresql/data"
      - "/data/postgres-restore:/var/data"
    restart: always
