version:docker-compose '2.0'
services:
  nginx:
    image: "nginx:1.9"
    ports:
      - 443:443
    links:
      - registry:registry
    volumes:
      - ./nginx/:/etc/nginx/conf.d:ro
    restart: always
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./data:/data
    restart: always
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE=Your Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - PULL_URL=https://your-reg.domain.com/
      - SINGLE_REGISTRY=false
      - DELETE_IMAGES=true
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    depends_on:
      - registry
    restart: always
