version: '3'
services:
  mysql:
    image: 'mysql:8.0.31'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
    volumes:
      - "/data/mysql:/var/lib/mysql"
      - "/data/mysql-restore:/var/data"
    restart: always
